import type { DocumentDetail } from './types';

function daysAgo(days: number): string {
  const date = new Date();
  date.setDate(date.getDate() - days);
  return date.toISOString().slice(0, 10);
}

export const demoDocuments: DocumentDetail[] = [
  {
    id: 1,
    original_filename: 'facture-atelier-mistral.pdf',
    supplier_name: 'Atelier Mistral',
    invoice_number: 'AM-2026-0921',
    invoice_date: daysAgo(2),
    due_date: daysAgo(-28),
    total_amount: '1008.00',
    currency: 'EUR',
    status: 'posted',
    created_at: daysAgo(2),
    file_url: null,
    mime_type: 'application/pdf',
    size_bytes: 128000,
    account_code: '606100',
    description: 'Fournitures d’atelier',
    subtotal: '840.00',
    vat_amount: '168.00',
  },
  {
    id: 2,
    original_filename: 'facture-studio-lune.pdf',
    supplier_name: 'Studio Lune',
    invoice_number: 'SL-2026-0118',
    invoice_date: daysAgo(5),
    due_date: daysAgo(-25),
    total_amount: '1440.00',
    currency: 'EUR',
    status: 'posted',
    created_at: daysAgo(5),
    file_url: null,
    mime_type: 'application/pdf',
    size_bytes: 132000,
    account_code: '622600',
    description: 'Honoraires de création',
    subtotal: '1200.00',
    vat_amount: '240.00',
  },
  {
    id: 3,
    original_filename: 'facture-transports-nord.pdf',
    supplier_name: 'Transports du Nord',
    invoice_number: 'TN-2026-0914',
    invoice_date: daysAgo(14),
    due_date: daysAgo(-16),
    total_amount: '336.00',
    currency: 'EUR',
    status: 'posted',
    created_at: daysAgo(14),
    file_url: null,
    mime_type: 'application/pdf',
    size_bytes: 115000,
    account_code: '624100',
    description: 'Transport de marchandises',
    subtotal: '280.00',
    vat_amount: '56.00',
  },
  {
    id: 4,
    original_filename: 'facture-epicerie-moderne.pdf',
    supplier_name: 'L’Épicerie Moderne',
    invoice_number: 'LEM-2026-0842',
    invoice_date: daysAgo(1),
    due_date: daysAgo(-29),
    total_amount: '384.50',
    currency: 'EUR',
    status: 'needs_review',
    created_at: daysAgo(1),
    file_url: null,
    mime_type: 'application/pdf',
    size_bytes: 145000,
    account_code: null,
    description: 'Achats de fournitures',
    subtotal: '320.42',
    vat_amount: '64.08',
  },
  {
    id: 5,
    original_filename: 'facture-bureau-clair.pdf',
    supplier_name: 'Bureau Clair',
    invoice_number: 'BC-2026-0730',
    invoice_date: daysAgo(3),
    due_date: daysAgo(-27),
    total_amount: '153.60',
    currency: 'EUR',
    status: 'needs_review',
    created_at: daysAgo(3),
    file_url: null,
    mime_type: 'application/pdf',
    size_bytes: 109000,
    account_code: null,
    description: 'Fournitures de bureau',
    subtotal: '128.00',
    vat_amount: '25.60',
  },
  {
    id: 6,
    original_filename: 'facture-cafe-des-arts.pdf',
    supplier_name: 'Café des Arts',
    invoice_number: 'CDA-2026-0591',
    invoice_date: daysAgo(6),
    due_date: daysAgo(-24),
    total_amount: '115.20',
    currency: 'EUR',
    status: 'needs_review',
    created_at: daysAgo(6),
    file_url: null,
    mime_type: 'application/pdf',
    size_bytes: 153000,
    account_code: null,
    description: 'Frais de réception',
    subtotal: '96.00',
    vat_amount: '19.20',
  },
  {
    id: 7,
    original_filename: 'facture-nuage-numerique.pdf',
    supplier_name: 'Nuage Numérique',
    invoice_number: 'NN-2026-3104',
    invoice_date: daysAgo(8),
    due_date: daysAgo(-22),
    total_amount: '58.80',
    currency: 'EUR',
    status: 'needs_review',
    created_at: daysAgo(8),
    file_url: null,
    mime_type: 'application/pdf',
    size_bytes: 101000,
    account_code: null,
    description: 'Abonnement logiciel',
    subtotal: '49.00',
    vat_amount: '9.80',
  },
  {
    id: 8,
    original_filename: 'facture-maison-des-plantes.pdf',
    supplier_name: 'Maison des Plantes',
    invoice_number: 'MDP-2026-1770',
    invoice_date: daysAgo(11),
    due_date: daysAgo(-19),
    total_amount: '258.00',
    currency: 'EUR',
    status: 'needs_review',
    created_at: daysAgo(11),
    file_url: null,
    mime_type: 'application/pdf',
    size_bytes: 126000,
    account_code: null,
    description: 'Entretien des locaux',
    subtotal: '215.00',
    vat_amount: '43.00',
  },
];
